version: '3.6'

services:
  api_relay_back_postgres_db:
    container_name: api_relay_back_postgres_db
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: vi_debt_back
      POSTGRES_DB: vi_debt_back
    volumes:
      - api_relay_back_volume_postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432


  api_relay_back_bot_adminer:
    container_name: api_relay_back_bot_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8890:8080
    environment:
      ADMINER_DEFAULT_SERVER: api_relay_back_postgres_db


  api_relay_back_app:
    container_name: api_relay_back_app
    image: api_relay_back_backend:latest
    restart: always
    depends_on:
      - api_relay_back_postgres_db
    environment:
      CONFIG: master
      SECRET_KEY:
      POSTGRES_PASSWORD:
    ports:
      - 83:80

volumes:
  api_relay_back_volume_postgres_db: