version: '3.6'

services:
  relay_back_postgres_db:
    container_name: relay_back_postgres_db
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: relay_back
      POSTGRES_DB: relay_back
    volumes:
      - relay_back_volume_postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  relay_back_bot_adminer:
    container_name: relay_back_bot_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8890:8080
    environment:
      ADMINER_DEFAULT_SERVER: relay_back_postgres_db

  relay_back_redis:
    container_name: relay_back_redis
    image: redis:6.2
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  relay_back_volume_postgres_db: